### ISSUE TITLE
qterminal preferences does not save checkbox status

### ISSUE THREAD

**Issue by lula123** [qterminal/qterminal#108]
Status of checkbox Actions -> Preferences -> Look and Feel -> Highligh(t) Current Terminal With Border is not saved. If you uncheck it, it is checked again after a restart of the program. I wasn't able to find any reference to the checkbox in .config/qterminal.org/qterminal.ini. As a side note: There's a "t" missing at the end of Highlight in the UI. Version 0.4.0, Mageia Cauldron

**Comment by worblehat** [comment]
I think this is already fixed, isn't it?
