### ISSUE TITLE
Confusing Tab Bar Settings

### ISSUE THREAD

**Issue by worblehat** [qterminal/qterminal#119]
Currently there are two settings affecting the visibility of the tab bar:

1. **Always show the tab bar** in preferences
2. **Show tab bar** in view menu

It took me a while to understand how these settings work. Especially because the former does not always show the tab bar (as it claims) when the latter is disabled.

Suggestions:

1. Rename the option in preferences to make clear, what it is doing. For example: "Hide tab bar when only one tab exists."

2. Or remove the option in preferences. Do we really need it? If you are working with only one tab and you are annoyed by the tab bar you can just disable **Show tab bar** anyway.

**Comment by iggy** [comment]
It's a pretty common setting amongst terminals (and other programs that use tabs). I'd say keep it and make it's wording more closely match that of other programs. The only reason I'd suggest getting rid of the option is if it's trouble to maintain the feature. Otherwise just making the settings/info better is a much better option.

**Comment by worblehat** [comment]
I agree its a common feature to hide the tab bar on one tab, but providing a setting for it is not that common I think. Here is what other terminal emulators do:

1. **Gnome-Terminal**: Only show tab bar for multiple tabs. Not configurable.
2. **lxterminal**: Only show tab bar for multiple tabs. Not configurable.
3. **Terminator**: Only show tab bar for multiple tabs. Not configurable.
4. **Konsole**: Provides a setting with 3 options: always show, always hide, only show when necessary

I personally think the approach of 1. - 3. is  a good one because it avoids unnecessary complexity for the user. For QTerminal that would mean: Remove the **Always show the tab bar** setting and automatically hide the task bar if only one tab exists.

**Comment by Vality** [comment]
@worblehat 
Just to add, I consider this feature so useful, I would find it extremely difficult to use any terminal emulator which did not provide it. I switched to q-terminal  from Konsole as it had a similar feature set but was lighter and less buggy.

I really hate it when a user interface unpredictably "moves around" and rearranges itself when I am performing activities which breaks my concentration and disrupts my ability to scan over the text.

Please leave this setting in, or if it must be removed at least make the default to keep the tab bar enabled always. This is one of the features which drew me to using q-terminal in the first place.

**Comment by worblehat** [comment]
@Vality 
I see your point.

One of the reasons I like QTerminal more than Konsole is the ability to toggle the task bar via the menu or a shortcut. That is important for me, because I usually work with the task bar hidden, but with a lot of opened tabs however a quick glance at the current tab structure is very useful. In Konsole that is not possible as you have to go to the preferences for this.

Now we have three different kinds of use cases here...
To please everyone I think my first suggestion from above might be convinient:

Don't change to much. Just rename the **Always show the tab bar** setting to something like **Hide tab bar with only on tab** and have it disabled by default.

**Comment by Vality** [comment]
@worblehat 

I certainly agree with that. That change would be an unambiguous improvement, easy to implement and fix the confusion issues. Thoroughly good idea.

**Comment by worblehat** [comment]
What does @pvanek think about this? I would create a pull request if you agree.

**Comment by pvanek** [comment]
it sounds good to me

**Comment by worblehat** [comment]
As the name of the `AlwaysShowTabs`-setting will change, I need to handle this in [migrate_settings()](https://github.com/qterminal/qterminal/blob/ce35bc6a54325ae6c86e5340a28e26a800c984eb/src/mainwindow.cpp#L101-120). 

Reading the current code of that method, I was wondering: What is this `version=0.4.0` in the settings for?
I guess it was introduced to only run the migration code in specific versions but nobody updated it afterwards.

It is not really necessary for the migration. Do you really want that version number in the settings? If yes, I will see how we can keep it up to date. Otherwise I could remove it.
