### ISSUE TITLE
moving tabs by drag & drop compromises terminals on exit

### ISSUE THREAD

**Issue by pmattern** [qterminal/qterminal#127]
If the order of tabs gets changed by drag & drop wrong terminals are closed on exit and remaining ones turn into a gray area.

Simple example how to reproduce: open a QTerminal window with two tabs 'Shell No. 1' and 'Shell No. 2' in that order, change the order by drag & drop, type 'exit' in one of the shells. Result will be that apparently the other shell / tab gets closed and the one where exit has been invoked turns into a gray area.
Similar findings can be made with more than two tabs as well.
Problem doesn't affect moving tabs by keyboard shortcuts.

Corresponding error message (launching QTerminal from another terminal emulator) is
> QProcess: Destroyed while process ("/bin/bash") is still running.

Latest Git versions of both QTermWidget and QTerminal compiled against Qt 5.3.2 or 5.4.0 on Arch Linux x86_64.

**Comment by jleclanche** [comment]
Confirmed, pretty critical too. I thought I opened a bug about it.
