### ISSUE TITLE
Feature Request: Send command to all windows

### ISSUE THREAD

**Issue by famewolf** [qterminal/qterminal#129]
Qterminal would make an excellent lightweight replacement for byobu if it had the ability to send the same command to all open windows.  This is very useful to perform apt update and apt dist-upgrade across multiple machines on a network.  (if this functionality is already present and I missed it my apologies)

**Comment by jleclanche** [comment]
rejecting this. realistically it won't happen, and if it does it won't be maintained. There's apps that can handle this sort of stuff a lot better than qterminal could.

**Comment by iggy** [comment]
Konsole does it (as do others). I know konsole feature parity isn't exactly a necessity, just mentioning it.
