### ISSUE TITLE
Setting 'Terminal Transparency' does not work.

### ISSUE THREAD

**Issue by worblehat** [qterminal/qterminal#133]
'Application Transparency' makes the whole application transparent. But 'Terminal Transparency' has no effect. I tested this with a KDE-desktop.

Can anyone confirm this?

**Comment by AcarBurak** [comment]
None is persistent in Fluxbox+Compton. Both transparencies work initially set in Preferences, but they revert back to 0 transparency when qterminal is relaunched. I need to re-enable them in Preferences every time.

**Comment by worblehat** [comment]
I can confirm this. You used the latest version from the repository, don't you?
It is related to the latest renaming of the transparency settings. I will fix this tomorrow. Thanks!

Back to the original question: Making the terminal transparent without making the whole application transparent works for you?

**Comment by AcarBurak** [comment]
Sorry to omit this. No, same as yours, as you've said in the first comment.

I use Arch AUR packages (qtermwidget-git and qterminal-git by jleclanche). 

Thank you.

**Comment by agaida** [comment]
Confirmed, latest git with Qt 5.3.2/5.4.1 on debian sid

**Comment by jleclanche** [comment]
dup of #138

**Comment by agaida** [comment]
hmm - build the latest version from git - transparency still not work so i reopen the bug
