### ISSUE TITLE
access menus by keyboard

### ISSUE THREAD

**Issue by pmattern** [qterminal/qterminal#137]
I think it would be helpful if menus were accessible by keyboard as well.
Just the ordinary way, namely open a menu by Alt+\<underlined letter\> ("mnemonic") and select items within open menus by hitting some underlined letter.

**Comment by worblehat** [comment]
I think that would be useful. I created a patch in case @pvanek agrees.

However there is one minor drawback: The shortcuts are hardcoded (with an ampersand in front of the mnemonic-letter). So the translations need to add them manually, too. Qt is able to create those Alt+<> shortcuts automatically, but they are often unintuitive and don't work for menu items added at runtime (as far as I know).

**Comment by jleclanche** [comment]
@worblehat I'd like to see your solution yes.
