### ISSUE TITLE
appearance: separate transparency of terminal widget with full opaque main window

### ISSUE THREAD

**Issue by antis81** [qterminal/qterminal#163]
The transparency values of the terminal widget and the main window can be set (both default to 0% == opaque).

Changing the value for the terminal's transparency has no effect at all -> :beetle: bug. Setting the main window's transparency works like expected, but I wish for a behaviour like in `lxterminal` (I think most terminal emulators), where just the terminal is transparent, while the app-window always is fully opaque.

This can be achieved similar to this example:
```c++
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
{
    // This makes the (widget area) background completely transparent, leaving the menu and tool bar untouched.
    this->setAttribute(Qt::WA_TranslucentBackground);
    this->setupUi(this);

    // the following flags might or might not be required (check them out):
    // terminal->setAttribute(Qt::WA_TranslucentBackground, false);
    // terminal->setAttribute(Qt::WA_OpaquePaintEvent);
    // terminal->setAutoFillBackground(true);
    terminal->setTerminalOpacity(.5);
}
```

Like expected, this only works with available compositing (I use `Compton` for X11).

Wrote a little test application for myself, playing with the values. To fake the terminal I used a simple QLabel with overriden `paintEvent`. Result looks like this:

![qterm-transparent-55](https://cloud.githubusercontent.com/assets/440517/8876269/ecf2b7a4-321e-11e5-98a7-6932b8c3a703.png)

... and fully tranparent:

![qterm-transparent-100](https://cloud.githubusercontent.com/assets/440517/8876281/f9086e58-321e-11e5-8086-f7f3627d445e.png)

**Comment by pvanek** [comment]
the pull request has been merged. Can we close this one?
