### ISSUE TITLE
XDG_CONFIG_DIRS support

### ISSUE THREAD

**Issue by Vladimir-csp** [qterminal/qterminal#174]
Please support setting default configuration via $XDG_CONFIG_DIRS.

**Comment by jleclanche** [comment]
That's already the case?

**Comment by Vladimir-csp** [comment]
I've tried copying config to /etc/xdg/qterminal.org/qterminal.ini and purging ~/.config/qterminal.org/, new instance was not configured.

**Comment by jleclanche** [comment]
I'm not sure we want to support the full xdg spec...

**Comment by agaida** [comment]
not the full spec - but at least QSettings would be a good start: lxqt/issues/385

**Comment by pvanek** [comment]
ok, I cannot say what can be reason to have the system-wide settings. But it works now. Actually it should work out of the box in Qt but some 3rd party patch changed the behavior years ago in qterminal...

**Comment by Vladimir-csp** [comment]
It helps a lot in administering multiple machines with multiple users. And it's a matter of predictability.
Thank you!

**Comment by agaida** [comment]
@pvanek - and additional it make distribution maintainers and the guys who build live isos happy - sensible systemwide defaults are cool :)
