### ISSUE TITLE
Display tabs in vertical list instead

### ISSUE THREAD

**Issue by sjlongland** [qterminal/qterminal#177]
Hi,

I've been using QTerminal for some time now, and find it a really effective terminal emulator.  I use it on a typical 1366×768 screen, and have a lot of tabs open usually.  Sometimes I find it hard to navigate because they spill off the end of the window.

I initially had the tabs laid out horizontally, then tried vertically down the left side.  While this works, it also rotates the labels.  My thinking was that if the labels were left horizontally oriented, it would make life a lot easier as more could be fit vertically down the screen.

Firing up Qt Designer, I had a tinker.  I see QTabWidget doesn't support this kind of layout, and digging around confirmed what I found:

http://stackoverflow.com/questions/14299651/qtabwidget-tabs-on-the-vertical-but-text-in-horizontal

Doing some tinkering, one layout that could work is this:
![qterm-tablist](https://cloud.githubusercontent.com/assets/1710526/10206473/67845060-680a-11e5-9116-41b94101555f.png)

Here, I used a QSplitter which allows the list view to be collapsed.  I might have a look later and see if it's feasible to add this functionality to QTerminal.

**Comment by jleclanche** [comment]
I don't think anyone would actually work on it, and even then I'd probably -1 it. It's a complex piece of work to support a very remote use case (even on browsers a lot of people don't use vtabs despite having hundreds of tabs open).

I'm closing this. Reopen it if you feel very strongly about it, but I'm not seeing this happen, sorry.

**Comment by pvanek** [comment]
patch can be accepted, implementation won't be too hard. On the other side I will not work on this one at all.
