### ISSUE TITLE
reset command does the same as clear

### ISSUE THREAD

**Issue by hotvic** [qterminal/qterminal#178]
When using QTerminal issuing the `reset` commands does the same as `clear`, i.e. after `reset` I can scroll and see whats was previously here the same as `clear`.

But IMO `reset` should clear the terminal scroll too. I've seen various terminals doing the same as QTerminal, is it a developer choose or something like this ? if yes, there's a way to disable it ? it's annoying for me: when I want to keep the output I just use `clear` but when not I type `reset` but QTerminal keep its there.

**Comment by jleclanche** [comment]
These commands are not builtin to QTerminal, they are part of your system. QTerminal is merely a terminal emulator which displays whatever the OS tells it to.

```
[4:01:21] adys@azura ~ % which reset
/usr/bin/reset
[4:01:23] adys@azura ~ % which clear
/usr/bin/clear
```

To clear the buffer from QTerminal itself, you can hit `Ctrl+Shift+X`.
