### ISSUE TITLE
Terminology in Preferences

### ISSUE THREAD

**Issue by anomaly256** [qterminal/qterminal#66]
Heyas,
Just a very minor issue: the settings for 'Application Transparency' and 'Terminal Transparency' are incorrectly titled - 100% transparency would mean the application is completely invisible but at the moment this means it's completely opaque.  These should probably be titled as 'Application Opacity' and 'Terminal Opacity', or the meaning of the value itself to be inverted so that 0% means completely opaque and 100% means completely transparent.

Feel free to take this suggestion on board or to ignore it as you see fit, as I said it's a minor issue :)

**Comment by worblehat** [comment]
I think the term 'transparency' should be used because not everyone knows what 'opacity' is.
I fixed it in my pull request. To be more consistent and to avoid confusion the term 'transparency' is also used everywhere in the source code now.
