### ISSUE TITLE
Use desktop actions instead of multiple desktop files for dropdown

### ISSUE THREAD

**Issue by jleclanche** [qterminal/qterminal#7]
http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s08.html

**Comment by antis81** [comment]
Is this related to #168?

**Comment by pvanek** [comment]
@jleclanche how it stays with its cross DE acceptance of these actions? I've never ever heard about any update...

**Comment by jleclanche** [comment]
Yeah this is abandoned. The xdg effort is pretty much dead at this point, really annoying.
